name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip of whole code
        run: |
          zip -r module.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/*"

      - name: Create GitHub Release and upload files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            module.zip \
            module.json \
            --title "${{ github.ref_name }}" \
            --notes "Automatic release"